name: Update AltStore repo JSON

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use default token

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Enable Debug Logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Run Update Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_json.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for Changes and Commit
        id: commit
        run: |
          git add sidestore_repo.json downloads/ resources/icons/
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changes=false" >> $GITHUB_ENV
          else
            git commit -m "Update SideStore JSON file and add new IPA"
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Push Changes
        if: env.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin HEAD:${{ github.ref }}

      - name: Upload JSON Artifact
        if: always()  # Ensure this runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: sidestore_repo.json
          path: sidestore_repo.json
