name: Update SideStore JSON

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Update Script
        env:
          GITHUB_TOKEN: ${{ secrets.SIDESTORE_UPDATE_TOKEN }}  # Use your secret name here
        run: python update_json.py
